model:
  file: ProtoNet
  name: ProtoNet
  strategy: Prototypical 
  input_channels: 1
  resize: 84

training:
  epochs: 30
  # batch_size: 32
  optimizer: Adam # Adam, AdamW, Lion
  learning_rate: 0.001
  weight_decay: 0.01
  early_stopping: 5

experiment:
  train_n_ways: 3
  val_n_ways: 3
  test_n_ways: 3
  n_shots: 5 # support set
  dataset: SAR_class_3 # miniImageNet, Fewshot-CIFAR100, SAR_class_3, SAR_class_6
  num_query: 15 # must be multiple of n_shots
  iterations: 300

paths:
  dataset_dir: './data'
  weight_dir: './weights'
  log_dir: './logs'
  
